export const ListOfFilm =[
    {id: 1, title:'Bác sĩ Cha', year: '2023', director: 'Kim Dae Jin', actor: 'Uhm Jung Hwa,Kim Byung Chul,Myung Se Bin,Min Woo Hyuk,Song Ji Ho,Kim Ye Eun,Jo Aram,Jo Eun Yoo', genre: 'Phim Tình Cảm, Phim Hài Hước',nation: 'Korean',type: 1, img: 'assets/images/DoctorCha.jpg', description: 'Bác sĩ Cha - Dr. Cha, Doctor Cha Jung Sook (VietSub - Thuyết Minh) kể lại câu chuyện Cha Jung Sook kết hôn với Seo In Ho, người làm bác sĩ phẫu thuật trưởng tại một bệnh viện đại học. Anh ấy có một tính cách nghiêm khắc, nhạy cảm và thấu đáo. Cha Jung Sook là một bà nội trợ toàn thời gian trong 20 năm qua, từ bỏ sự nghiệp bác sĩ trong những năm nội trú y khoa. Sau ngần ấy năm, cô quyết định bắt đầu lại khóa học bác sĩ nội trú của mình.'},
    {id: 2, title:'Love & Death', year: '2023', director: 'Lesli Linka Glatter, Clark Johnson', actor: ' Elizabeth Olsen, Jesse Plemons, Lily Rabe, Patrick Fugit ,Krysten Ritter, Tom Pelphrey ,Elizabeth Marvel ,Keir Gilchrist', genre: 'Tâm lý',nation: 'American', type: 1, img: 'assets/images/Love&Death.jpg', description: 'Love & Death là một bộ phim truyền hình ngắn tập về tội phạm của Mỹ do Lesli Linka Glatter và Clark Johnson đạo diễn, David E. Kelley viết kịch bản, công chiếu vào ngày 27 tháng 4 năm 2023, trên HBO Max'},
    {id: 3, title:'Black Adam', year: '2022',director: '', actor: '', genre: '', nation: 'American', type: 0,  img: 'assets/images/BlackAdam.jpg', description: ''}, 
    {id: 4, title:'My Blue Summer', year: '2022',director: '', actor: '', genre: '', nation: 'China',  type: 0, img: 'assets/images/MyBlueSummer.jpg', description: ''},
    {id: 5, title:'Kịch Trường của Takemichi', year: '2021', director: '', actor: '', genre: '',nation: 'Japan', type: 0,  img: 'assets/images/KichTruongCuaTakemichi.jpg', description: ''},
    {id: 6, title:'Bộ đôi sấm sét', year: '2021',director: '', actor: '', genre: '', nation: 'American', type: 0,  img: 'assets/images/BoDoiSamSet.jpg', description: ''},
    {id: 7, title:'Shazam 2: Cơn thịnh nộ của các vị thần', year: '2023', director: '', actor: '', genre: '',nation: 'American',  type: 0, img: 'assets/images/Shazam2.jpg', description: ''},
    {id: 8, title:'High & Low the worst X ', year: '2023', director: '', actor: '', genre: '',nation: 'Japan', type: 0,  img: 'assets/images/HighAndLow.jpg', description: ''},
    {id: 9, title:'OMG! OH My Girl', year: '2023',director: '', actor: '', genre: '', nation: 'Thailand',  type: 0, img: 'assets/images/OMG.jpg',  description: ''},
];